import 'package:flutter/material.dart';

const String title = "Hoşgeldiniz!",
    subtitle = "Lütfen öncelikle giriş yapınız👋",
    email = "Email",
    login = "Giriş Yap",
    sifre = "Şifre",
    forgotPassword = "Şifremi Unuttum",
    textLabel2 = 'abc@xyz.com',
    textLabel3 = 'Şifrenizi Girin',
    loginWithAccount = 'Hesabınızla Giriş Yapın',
    dontHaveAccount = 'Henüz bir hesabınız yok mu?',
    emailAlert = "E-Posta Alanı Boş Bırakılamaz!",
    emailAlertSubtitle = "Lütfen e-postanızı girin.",
    passwordAlert = "Şifre Alanı Boş Bırakılamaz!",
    passwordAlertSubtitle = "Lütfen şifrenizi girin.",
    userNotFound = "Kullanıcı Bulunamadı!",
    userNotFoundSubtitle =
        "Hesabınız yoksa aşağıdaki kayıt ol butonunu kullanarak kayıt olabilirsiniz.",
    wrongPassword = "Şifre Yanlış!",
    wrongPasswordSubtitle =
        "Şifrenizi yanlış girdiniz, lütfen tekrar deneyin...",
    enterEmailHint = "E-posta adresinizi girin.",
    enterEmail =
        "Şifresini sıfırlamak istediğiniz hesabınızın e-mail adresini girin:",
    checkEmail = 'E-posta adresinizi kontrol edin.',
    invalidEmail = "Geçersiz E-Mail Adresi!",
    invalidEmailSubtitle = "Lütfen geçerli bir E-Mail adresi girin.",
    register = "Kayıt Ol!",
    subtitle2 = "Aşağıdaki alanları doldurarak kaydolabilirsiniz.🙂",
    name = "Ad",
    surname = "Soyad",
    password = "Şifre",
    yourName = "Adınız",
    yourSurname = "Soyadınız",
    yourBirthday = "Doğum Tarihiniz",
    weakPassword = "Güçsüz Şifre!",
    weakPasswordSubtitle = "Girdiğiniz şifre minimum 6 haneden oluşmalı!",
    emailAlreadyInUse = "Geçersiz E-Posta!",
    emailAlreadyInUseSubtitle =
        "Girdiğiniz E-posta adresi başka bir hesaba bağlı!",
    nameAlert = "İsim Alanı Boş Bırakılamaz!",
    nameAlertSubtitle = "Lütfen isminizi girin.",
    surnameAlert = "Soy İsim Alanı Boş Bırakılamaz!",
    surnameAlertSubtitle = "Lütfen soy isminizi girin.",
    birthdayAlert = "Doğum Tarihi Alanı Boş Bırakılamaz!",
    birthdayAlertSubtitle = "Lütfen doğum tarihinizi seçin.",
    confirmButtonText = "Kapat",
    alertTitle = "Görev Çöp Kutusuna Taşınacak!",
    alertSubtitle = "Görev çöp kutusuna taşınsın mı?",
    alertApprove = "Onayla",
    alertReject = "İptal Et",
    alertTitleLogOut = "Çıkış Yapılacak!",
    alertSubtitleLogOut = "Çıkış yapmak istediğinizden emin misiniz?",
    changePassword = "Şifreyi Değiştir",
    subtitle3 = "Aşağıdaki alanları doldurarak şifrenizi yenileyebilirsiniz 🙂",
    oldPassword = "Eski Şifre",
    oldPasswordHint = "Eski Şifrenizi Girin",
    newPasswordText = "Yeni Şifre",
    passwordHint = "Yeni Şifrenizi Girin",
    oldPasswordAlert = "Eski Şifre Alanı Boş Bırakılamaz!",
    oldPasswordAlertSubtitle = "Lütfen eski şifrenizi girin.",
    newPasswordAlert = "Yeni Şifre Alanı Boş Bırakılamaz!",
    newPasswordAlertSubtitle = "Lütfen yeni şifrenizi girin.",
    passwordConfirmed = 'Şifreniz Başarıyla Değiştirildi.',
    passwordConfirmedSubtitle =
        'Lütfen yeni şifrenizi kullanarak tekrar giriş yapınız.',
    taskPageTitle = "Görev Düzenleme Sayfası",
    taskPageSubtitle =
        "Görevin ismi,türü ve açıklamasını düzenleyebilirsiniz👋",
    taskPageTaskName = "Görev İsmi",
    taskPageTaskType = "Görev Türü",
    taskPageTaskInfo = "Görev Açıklaması",
    isTaskDone = 'Görev tamamlandı mı?',
    isTaskArchive = 'Görev arşivlensin mi?',
    taskMovedIntoArchive = "Görev arşive taşındı!",
    taskMovedIntoCompleted = "Görev tamamlanmış görevler sayfasına taşındı!",
    updateButtonText = "Güncelle",
    pomodoroTitle = "Pomodoro Ayarları",
    pomodoroSubtitle =
        "Aşağıdaki alanlardan pomodoro zamanlayıcısının ayarlarını yapabilirsiniz.🙂",
    workTimer = "Çalışma Zamanı Süresi",
    breakTimer = "Mola Süresi",
    longBreakTimer = "Uzun Mola Süresi",
    longBreakNumber = "Uzun Molanın Kaçıncı Arada Verileceği",
    workTimerSelect = "Çalışma Zamanı Süresini Seçiniz",
    breakTimerSelect = "Mola Süresini Seçiniz",
    longBreakTimerSelect = "Uzun Mola Süresini Seçiniz",
    longBreakNumberSelect = "Uzun Molanın Kaçıncı Arada Verileceğini Seçiniz",
    minute = "dakika",
    noResult = 'Sonuç Bulunamadı!',
    moveIntoTrash = "ÇÖP KUTUSUNA TAŞI",
    editText = "DÜZENLE",
    noActiveTask = "Aktif görev bulunamadı!",
    noTask = 'Görev bulunamadı!',
    addButtonText = "Ekle",
    editProfileTitle = "Profil Düzenleme",
    editProfileSubtitle = "Kişisel bilgilerinizi düzenleyebilirsiniz👋",
    editProfileName = "Adınız",
    editProfileSurname = "Soyadınız",
    editProfileBirthday = "Doğum Tarihiniz",
    nameOfTask = 'Görev adı',
    typeOfTask = 'Görev türü',
    infoOfTask = 'Görev açıklaması...',
    buttonText = "Kaydet",
    statisticsTitle = "İstatistikler";
    
const List<String> workTimerList = [
      '20 dakika',
      '25 dakika',
      '30 dakika',
      '35 dakika',
      '40 dakika'
    ],
    breakTimerList = [
      '5 dakika',
      '6 dakika',
      '7 dakika',
      '8 dakika',
      '9 dakika',
      '10 dakika'
    ],
    longBreakTimerList = [
      '15 dakika',
      '16 dakika',
      '17 dakika',
      '18 dakika',
      '19 dakika',
      '20 dakika'
    ],
    longBreakNumberList = ['1', '2', '3', '4', '5'];

const Color kLightGrey = Color.fromRGBO(238, 238, 238, 1),
    kLightGreen = Color.fromRGBO(198, 228, 139, 1),
    kMidGreen = Color.fromRGBO(123, 201, 111, 1),
    kDarkGreen = Color.fromRGBO(35, 154, 59, 1),
    kDarkerGreen = Color.fromRGBO(25, 97, 39, 1);
