// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdY2gxZn5bdR6MDuiPmRx8EW3Fv5SKlo0',
    appId: '1:564579364345:web:04358159ae830e8d476128',
    messagingSenderId: '564579364345',
    projectId: 'pomotodo-f236a',
    authDomain: 'pomotodo-f236a.firebaseapp.com',
    databaseURL: 'https://pomotodo-f236a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pomotodo-f236a.appspot.com',
    measurementId: 'G-JWDDMTEBPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATYp93dobUuYCMWCUsHdpYwEnFnZTK6hA',
    appId: '1:564579364345:android:eea0b3ac91f0b2ad476128',
    messagingSenderId: '564579364345',
    projectId: 'pomotodo-f236a',
    databaseURL: 'https://pomotodo-f236a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pomotodo-f236a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhe9NTSK8oTWdhx27h3D4NFrTtQs53GnE',
    appId: '1:564579364345:ios:2708d5a49f1290cf476128',
    messagingSenderId: '564579364345',
    projectId: 'pomotodo-f236a',
    databaseURL: 'https://pomotodo-f236a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pomotodo-f236a.appspot.com',
    iosClientId: '564579364345-hjt9ktssi2f3pp4kn94vkslsic0cfrs2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhe9NTSK8oTWdhx27h3D4NFrTtQs53GnE',
    appId: '1:564579364345:ios:2708d5a49f1290cf476128',
    messagingSenderId: '564579364345',
    projectId: 'pomotodo-f236a',
    databaseURL: 'https://pomotodo-f236a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pomotodo-f236a.appspot.com',
    iosClientId: '564579364345-hjt9ktssi2f3pp4kn94vkslsic0cfrs2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
