// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb4RiYufpyDDBNWeHt2jkJiY4Fe5sQGkg',
    appId: '1:238337804993:android:705bc0e5e30aa002d92240',
    messagingSenderId: '238337804993',
    projectId: 'pomo2do',
    storageBucket: 'pomo2do.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrlJWG4q4CsttY5ajk3E2tn6LYhs6kvDQ',
    appId: '1:238337804993:ios:7db08342b75405bcd92240',
    messagingSenderId: '238337804993',
    projectId: 'pomo2do',
    storageBucket: 'pomo2do.appspot.com',
    androidClientId: '238337804993-19903bmpiq753gr1evdihp6l5a8ekema.apps.googleusercontent.com',
    iosClientId: '238337804993-44vaig6hejp578e2i4nvcgg5s7e7qae5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
