const String title = "Hoşgeldiniz!",
    subtitle = "Lütfen öncelikle giriş yapınız👋",
    email = "Email",
    sifre = "Şifre",
    forgotPassword = "Şifremi Unuttum",
    textLabel2 = 'abc@xyz.com',
    textLabel3 = 'Şifrenizi Girin',
    loginWithAccount = 'Hesabınızla Giriş Yapın',
    dontHaveAccount = 'Henüz bir hesabınız yok mu?',
    emailAlert = "E-Posta Alanı Boş Bırakılamaz!",
    emailAlertSubtitle = "Lütfen e-postanızı girin.",
    passwordAlert = "Şifre Alanı Boş Bırakılamaz!",
    passwordAlertSubtitle = "Lütfen şifrenizi girin.",
    userNotFound = "Kullanıcı Bulunamadı!",
    userNotFoundSubtitle =
        "Hesabınız yoksa aşağıdaki kayıt ol butonunu kullanarak kayıt olabilirsiniz.",
    wrongPassword = "Şifre Yanlış!",
    wrongPasswordSubtitle =
        "Şifrenizi yanlış girdiniz, lütfen tekrar deneyin...",
    enterEmailHint = "E-posta adresinizi girin.",
    enterEmail =
        "Şifresini sıfırlamak istediğiniz hesabınızın e-mail adresini girin:",
    checkEmail = 'E-posta adresinizi kontrol edin.',
    invalidEmail = "Geçersiz E-Mail Adresi!",
    invalidEmailSubtitle = "Lütfen geçerli bir E-Mail adresi girin.",
     register = "Kayıt Ol",
     subtitle2 = "Aşağıdaki alanları doldurarak kaydolabilirsiniz.🙂",
     name = "Ad",
     surname = "Soyad",
     password = "Şifre",
     yourName = "Adınız",
     yourSurname = "Soyadınız",
     yourBirthday = "Doğum Tarihiniz",
     weakPassword = "Güçsüz Şifre!",
     weakPasswordSubtitle = "Girdiğiniz şifre minimum 6 haneden oluşmalı!",
     emailAlreadyInUse = "Geçersiz E-Posta!",
     emailAlreadyInUseSubtitle =
        "Girdiğiniz E-posta adresi başka bir hesaba bağlı!",
     nameAlert = "İsim Alanı Boş Bırakılamaz!",
     nameAlertSubtitle = "Lütfen isminizi girin.",
     surnameAlert = "Soy İsim Alanı Boş Bırakılamaz!",
     surnameAlertSubtitle = "Lütfen soy isminizi girin.",
     birthdayAlert = "Doğum Tarihi Alanı Boş Bırakılamaz!",
     birthdayAlertSubtitle = "Lütfen doğum tarihinizi seçin.",
     confirmButtonText = "Kapat";
